# base/main-service/service-stable.yaml
apiVersion: v1
kind: Service
metadata:
  name: main-service-stable # 안정 버전 서비스 이름
spec:
  ports:
    - port: 80
      targetPort: http # 컨테이너 포트 이름
      protocol: TCP
      name: http
  selector:
    app: main-service # Rollout 의 .spec.selector.matchLabels 와 일치