# overlays/production/main-service/external-secret-main.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: main-service-kong-jwt-credential-eso
  namespace: dangdang-where-going
spec:
  secretStoreRef:
    name: aws-sm-store
    kind: ClusterSecretStore
  target:
    name: main-service-consumer-jwt-for-kong
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        annotations:
          konghq.com/credential: "main-service-consumer"

      data:
        kongCredType: "and0"
        key: "YXBwLXNlY3JldC1rZXktaWQ="
        algorithm: "SFMyNTY="


  data:
    - secretKey: secret
      remoteRef:
        key: doong
        property: kong