# overlays/production/main-service/ingress-nginx-kong.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-service-nginx-ingress
  namespace: dangdang-where-going
  annotations:
    kubernetes.io/ingress.class: nginx
    # '/main-api' 접두사를 제거하고 나머지 경로($2)만 Kong으로 전달하도록 수정 (주석 해제)
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: main.prod.your-domain.com # 실제 도메인으로 변경 필요
      http:
        paths:
          # Kong으로 전달할 경로 패턴
          - path: /main-api(/|$)(.*) # '/main-api' 로 시작하는 모든 경로
            pathType: Prefix
            backend:
              service:
                name: kong-proxy
                port:
                  number: 80