# overlays/production/main-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dangdang-where-going # 네임스페이스 지정

resources:
  - ../../../base/main-service
  # 환경별 리소스 추가
  - ingress-alb.yaml
  - ingress-nginx-kong.yaml     # rewrite-target 활성화된 버전 사용 권장
  - kong-service-main.yaml      # main-service 용 KongService (포트 확인!)
  - kong-ingress-main-public.yaml # Public 경로용 KongIngress <--- 추가
  - kong-ingress-main-private.yaml # Private 경로용 KongIngress <--- 추가
  - external-secret-main.yaml

patchesStrategicMerge:
  - rollout-patch.yaml

images:
  - name: main-service
    newName: app_repo_ecr
    newTag: placeholder