# overlays/production/common/external-secret-kong-jwt.yaml (NEW FILE)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-jwt-secret-sync
  namespace: kong
spec:
  secretStoreRef:
    name: aws-sm-store
    kind: ClusterSecretStore
    refreshInterval: "5m"

  target:
    name: my-jwt-shared-secret-from-eso
    creationPolicy: Owner
  data:
    - secretKey: kong # 최종 K8s Secret 안에 생성될 데이터의 Key 이름 ('kong'으로 지정해야 KongCredential과 호환됨)
      remoteRef:
        key: doong
        property: kong