# overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # 각 서비스의 Production 오버레이 디렉토리 참조
  - ./main-service
  - ./common